#
# NTU SC2002 FOMS
# CI Pipeline
#

on: push
jobs:
  lint:
    name: "Lint FOMS"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
          architecture: x64
      - name: Lint code style
        run: mvn spotless:check

  build-test:
    name: "Build & Test FOMS"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
          architecture: x64
      - name: Build FOMS
        run: mvn compile
      - name: Test FOMS
        run: mvn test
